groups:

- name: BlackboxExporter

  rules:

    - alert: BlackboxProbeFailed
      expr: 'probe_success == 0'
      for: 5m 
      labels:
        severity: critical
      annotations:
        summary: Blackbox probe icmp failed
        description: "Probe failed\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

    - alert: BlackboxConfigurationReloadFailure
      expr: 'blackbox_exporter_config_last_reload_successful != 1'
      for: 10m
      labels:
        severity: warning
      annotations:
        summary: Blackbox configuration reload failure
        description: "Blackbox configuration reload failure\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

    - alert: BlackboxSlowProbe
      expr: 'avg_over_time(probe_duration_seconds[1m]) > 20'
      for: 10m
      labels:
        severity: warning
      annotations:
        summary: Blackbox slow probe
        description: "Blackbox probe took more than 1s to complete\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

    - alert: BlackboxProbeHttpFailure
      expr: 'probe_http_status_code <= 199 OR probe_http_status_code >= 400'
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: Blackbox probe HTTP failure
        description: "HTTP status code is not 200-399\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

    - alert: BlackboxProbeSlowHttp
      expr: 'avg_over_time(probe_http_duration_seconds[1m]) > 10'
      for: 10m
      labels:
        severity: warning
      annotations:
        summary: Blackbox probe slow HTTP
        description: "HTTP request took more than 1s\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

    - alert: BlackboxProbeSlowPing
      expr: 'avg_over_time(probe_icmp_duration_seconds[1m]) > 10'
      for: 10m
      labels:
        severity: warning
      annotations:
        summary: Blackbox probe slow ping
        description: "Blackbox ping took more than 1s\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
